/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.campingapp.view;

/**
 *
 * @author Venuki Jayathilaka
 */
public class CampsiteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CampsiteFrame.class.getName());

    /**
     * Creates new form CampsiteFrame
     */
    public CampsiteFrame() {
        initComponents();
        loadCampsites();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddCampsite = new javax.swing.JButton();
        txtSiteName = new javax.swing.JTextField();
        txtSiteType = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JTextField();
        scrollPaneCampsites = new javax.swing.JScrollPane();
        tblCampsites = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Campsite Management ");

        jLabel2.setText("Site Name:");

        jLabel3.setText("Site Type:");

        jLabel4.setText("Price/Night:");

        jLabel5.setText("Capacity:");

        btnAddCampsite.setText("Add Campsite");
        btnAddCampsite.addActionListener(this::btnAddCampsiteActionPerformed);

        txtSiteName.addActionListener(this::txtSiteNameActionPerformed);

        txtSiteType.addActionListener(this::txtSiteTypeActionPerformed);

        txtCapacity.addActionListener(this::txtCapacityActionPerformed);

        tblCampsites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneCampsites.setViewportView(tblCampsites);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnAddCampsite))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSiteType, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneCampsites, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSiteType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(btnAddCampsite))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(scrollPaneCampsites, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSiteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiteNameActionPerformed

    private void txtSiteTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiteTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiteTypeActionPerformed

    private void txtCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacityActionPerformed

    private void btnAddCampsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCampsiteActionPerformed
String siteName = txtSiteName.getText().trim();
String siteType = txtSiteType.getText().trim();
String priceText = txtPrice.getText().trim();
String capacityText = txtCapacity.getText().trim();

if (siteName.isEmpty() || siteType.isEmpty() || priceText.isEmpty() || capacityText.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "All fields are required.");
    return;
}

try {
    java.math.BigDecimal price = new java.math.BigDecimal(priceText);
    int capacity = Integer.parseInt(capacityText);

    com.campingapp.model.Campsite campsite = new com.campingapp.model.Campsite();
    campsite.setSiteName(siteName);
    campsite.setSiteType(siteType);
    campsite.setPricePerNight(price);
    campsite.setCapacity(capacity);
    campsite.setStatus("Available");

    com.campingapp.dao.CampsiteDAO dao = new com.campingapp.dao.CampsiteDAO();
    dao.addCampsite(campsite);

    javax.swing.JOptionPane.showMessageDialog(this, "Campsite added successfully!");

    txtSiteName.setText("");
    txtSiteType.setText("");
    txtPrice.setText("");
    txtCapacity.setText("");

    loadCampsites();

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Price and Capacity must be valid numbers.");
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error adding campsite: " + e.getMessage());
}        
    }//GEN-LAST:event_btnAddCampsiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CampsiteFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCampsite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane scrollPaneCampsites;
    private javax.swing.JTable tblCampsites;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSiteName;
    private javax.swing.JTextField txtSiteType;
    // End of variables declaration//GEN-END:variables
private void loadCampsites() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Site Name");
    model.addColumn("Type");
    model.addColumn("Price/Night");
    model.addColumn("Capacity");
    model.addColumn("Status");

    try {
        com.campingapp.dao.CampsiteDAO dao = new com.campingapp.dao.CampsiteDAO();
        java.util.List<com.campingapp.model.Campsite> campsites = dao.getAllCampsites();
        for (com.campingapp.model.Campsite c : campsites) {
            model.addRow(new Object[]{
                c.getCampsiteId(), c.getSiteName(), c.getSiteType(),
                c.getPricePerNight(), c.getCapacity(), c.getStatus()
            });
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading campsites: " + e.getMessage());
    }

    tblCampsites.setModel(model);
  }
}

