/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.campingapp.view;

/**
 *
 * @author Venuki Jayathilaka
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageCustomers = new javax.swing.JButton();
        btnManageCampsites = new javax.swing.JButton();
        btnNewReservation = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Camping Site Reservation System - Dashboard");

        btnManageCustomers.setText("Manage Customers");
        btnManageCustomers.addActionListener(this::btnManageCustomersActionPerformed);

        btnManageCampsites.setText("Manage Campsites");
        btnManageCampsites.addActionListener(this::btnManageCampsitesActionPerformed);

        btnNewReservation.setText("New Reservation");
        btnNewReservation.addActionListener(this::btnNewReservationActionPerformed);

        btnViewReport.setText("View Reservation Report");
        btnViewReport.addActionListener(this::btnViewReportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnNewReservation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageCampsites, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnManageCustomers)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnViewReport)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnManageCustomers)
                .addGap(28, 28, 28)
                .addComponent(btnManageCampsites)
                .addGap(35, 35, 35)
                .addComponent(btnNewReservation)
                .addGap(42, 42, 42)
                .addComponent(btnViewReport)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
new com.campingapp.view.CustomerFrame().setVisible(true);        
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReservationActionPerformed
new com.campingapp.view.ReservationFrame().setVisible(true);        
    }//GEN-LAST:event_btnNewReservationActionPerformed

    private void btnManageCampsitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCampsitesActionPerformed
new com.campingapp.view.CampsiteFrame().setVisible(true);        
    }//GEN-LAST:event_btnManageCampsitesActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
try {
    java.util.Map<String, Object> parameters = new java.util.HashMap<>();

    net.sf.jasperreports.engine.JasperReport jasperReport =
        (net.sf.jasperreports.engine.JasperReport) net.sf.jasperreports.engine.util.JRLoader.loadObject(
            new java.io.File("C:\\NetBeansProjects\\CampingReservationSystem\\src\\ReservationSummary.jasper"));

    net.sf.jasperreports.engine.JasperPrint jasperPrint =
        net.sf.jasperreports.engine.JasperFillManager.fillReport(
            jasperReport, parameters, com.campingapp.util.DatabaseConnection.getConnection());

    net.sf.jasperreports.swing.JRViewer viewer = new net.sf.jasperreports.swing.JRViewer(jasperPrint);

    javax.swing.JFrame reportFrame = new javax.swing.JFrame("Reservation Report");
    reportFrame.add(viewer);
    reportFrame.setSize(800, 600);
    reportFrame.setLocationRelativeTo(this);
    reportFrame.setVisible(true);

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage());
    e.printStackTrace();
}        
    }//GEN-LAST:event_btnViewReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCampsites;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnNewReservation;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
