/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.campingapp.view;

/**
 *
 * @author Venuki Jayathilaka
 */
public class ReservationFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservationFrame.class.getName());

    /**
     * Creates new form ReservationFrame
     */
    public ReservationFrame() {
        initComponents();
        loadCustomerDropdown();
        loadCampsiteDropdown();
        loadReservations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneReservations = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCampsite = new javax.swing.JComboBox<>();
        txtCheckIn = new javax.swing.JTextField();
        txtCheckOut = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneReservations.setViewportView(tblReservations);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("New Reservation");

        jLabel2.setText("Customer:");

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Campsite:");

        jLabel4.setText("Check-in Date (yyyy-mm-dd):");

        jLabel5.setText("Check-out Date (yyyy-mm-dd):");

        cmbCampsite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCheckIn.addActionListener(this::txtCheckInActionPerformed);

        jLabel6.setText("Total Cost:");

        lblTotalCost.setText("0.00");

        btnCalculate.setText("Calculate Cost");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnConfirm.setText("Confirm Reservation");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCampsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConfirm)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTotalCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCheckOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCalculate)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCampsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalCost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnConfirm))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
try {
    int customerIndex = cmbCustomer.getSelectedIndex();
    int campsiteIndex = cmbCampsite.getSelectedIndex();

    if (customerIndex == -1 || campsiteIndex == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a customer and campsite.");
        return;
    }

    com.campingapp.model.Customer selectedCustomer = customerList.get(customerIndex);
    com.campingapp.model.Campsite selectedCampsite = campsiteList.get(campsiteIndex);

    java.sql.Date checkIn = java.sql.Date.valueOf(txtCheckIn.getText().trim());
    java.sql.Date checkOut = java.sql.Date.valueOf(txtCheckOut.getText().trim());

    long nights = (checkOut.getTime() - checkIn.getTime()) / (1000 * 60 * 60 * 24);
    if (nights <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Check-out date must be after check-in date.");
        return;
    }

    java.math.BigDecimal totalCost = selectedCampsite.getPricePerNight().multiply(java.math.BigDecimal.valueOf(nights));

    com.campingapp.model.Reservation reservation = new com.campingapp.model.Reservation();
    reservation.setCustomerId(selectedCustomer.getCustomerId());
    reservation.setCampsiteId(selectedCampsite.getCampsiteId());
    reservation.setCheckIn(checkIn);
    reservation.setCheckOut(checkOut);
    reservation.setTotalCost(totalCost);
    reservation.setStatus("Booked");

    com.campingapp.dao.ReservationDAO dao = new com.campingapp.dao.ReservationDAO();
    dao.addReservation(reservation);

    javax.swing.JOptionPane.showMessageDialog(this, "Reservation confirmed! Total: " + totalCost);

    txtCheckIn.setText("");
    txtCheckOut.setText("");
    lblTotalCost.setText("0.00");
    loadReservations();

} catch (com.campingapp.exception.ReservationConflictException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Booking failed: " + e.getMessage());
} catch (IllegalArgumentException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid dates in format yyyy-mm-dd.");
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
try {
    int selectedIndex = cmbCampsite.getSelectedIndex();
    if (selectedIndex == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a campsite.");
        return;
    }

    com.campingapp.model.Campsite selectedCampsite = campsiteList.get(selectedIndex);

    java.sql.Date checkIn = java.sql.Date.valueOf(txtCheckIn.getText().trim());
    java.sql.Date checkOut = java.sql.Date.valueOf(txtCheckOut.getText().trim());

    long nights = (checkOut.getTime() - checkIn.getTime()) / (1000 * 60 * 60 * 24);

    if (nights <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Check-out date must be after check-in date.");
        return;
    }

    java.math.BigDecimal totalCost = selectedCampsite.getPricePerNight().multiply(java.math.BigDecimal.valueOf(nights));
    lblTotalCost.setText(totalCost.toString());

} catch (IllegalArgumentException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid dates in format yyyy-mm-dd.");
}        
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReservationFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cmbCampsite;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JScrollPane scrollPaneReservations;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTextField txtCheckIn;
    private javax.swing.JTextField txtCheckOut;
    // End of variables declaration//GEN-END:variables
private java.util.List<com.campingapp.model.Customer> customerList;
private java.util.List<com.campingapp.model.Campsite> campsiteList;

private void loadCustomerDropdown() {
    try {
        com.campingapp.dao.CustomerDAO dao = new com.campingapp.dao.CustomerDAO();
        customerList = dao.getAllCustomers();
        cmbCustomer.removeAllItems();
        for (com.campingapp.model.Customer c : customerList) {
            cmbCustomer.addItem(c.getCustomerId() + " - " + c.getFullName());
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
    }
}

private void loadCampsiteDropdown() {
    try {
        com.campingapp.dao.CampsiteDAO dao = new com.campingapp.dao.CampsiteDAO();
        campsiteList = dao.getAllCampsites();
        cmbCampsite.removeAllItems();
        for (com.campingapp.model.Campsite c : campsiteList) {
            cmbCampsite.addItem(c.getCampsiteId() + " - " + c.getSiteName() + " ($" + c.getPricePerNight() + "/night)");
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading campsites: " + e.getMessage());
    }
}

private void loadReservations() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Customer ID");
    model.addColumn("Campsite ID");
    model.addColumn("Check-in");
    model.addColumn("Check-out");
    model.addColumn("Total Cost");
    model.addColumn("Status");

    try {
        com.campingapp.dao.ReservationDAO dao = new com.campingapp.dao.ReservationDAO();
        java.util.List<com.campingapp.model.Reservation> reservations = dao.getAllReservations();
        for (com.campingapp.model.Reservation r : reservations) {
            model.addRow(new Object[]{
                r.getReservationId(), r.getCustomerId(), r.getCampsiteId(),
                r.getCheckIn(), r.getCheckOut(), r.getTotalCost(), r.getStatus()
            });
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading reservations: " + e.getMessage());
    }

    tblReservations.setModel(model);
  }
}
